In [5]:
# NumPy -- Library for numerical computing

import numpy as np
print(np.__version__)

2.2.3


In [8]:
# 1D array

arr = np.array([10,20,30,40,50])
print(arr)
print('Type :', type(arr))
print('Shape :',arr.shape) 

[10 20 30 40 50]
Type : <class 'numpy.ndarray'>
Shape : (5,)


In [17]:
# 2D array
arr2 = np.array([[1,2,3,4],[4,5,6,7]])
print(arr2)

print('Shape :',arr2.shape)
print('Size :',arr2.size)
print(arr2[0])
print(arr2[0][2])

[[1 2 3 4]
 [4 5 6 7]]
Shape : (2, 4)
Size : 8
[1 2 3 4]
3


In [28]:
# Generate Arrays

arr1 = np.zeros((2,3))
print(arr1)

arr2 = np.ones((3,4))
print(arr2)

print(arr2[0][1])

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
1.0


In [33]:
arr3 = np.arange(1,10,3)
print(arr3)

[1 4 7]


In [34]:
sample = np.array([np.arange(1,20,5), np.arange(2,10,2)])
print(sample)

[[ 1  6 11 16]
 [ 2  4  6  8]]


In [42]:
# Operations

arr4 = np.arange(1,10,3)
arr5 = np.arange(2,10,3)

print(arr5+arr4)
print((arr5 * arr4))
print((arr4 ** 2))

[ 3  9 15]
[ 2 20 56]
[ 1 16 49]


In [40]:
purchases = np.array([
    [200,150,100],[300,250,400],[100,200,150],[500,600,550],[50,80,100]])

total_spend = purchases.sum(axis = 1)

average_spend = purchases.mean(axis = 1)

print('Total Spend :', total_spend)
print('Average Spend :', average_spend)
print(max(average_spend))

Total Spend : [ 450  950  450 1650  230]
Average Spend : [150.         316.66666667 150.         550.          76.66666667]
550.0


In [44]:
# 2x + 3y = 8
# 4x + y = 10

# Coefficients of variables
A = np.array([[2,3],[4,1]])

# Constants on right side
B = np.array([17,19])

# Solve for x and y
solution = np.linalg.solve(A,B) # linalg -- linear algorithm
print('Solution (x,y):', solution)

Solution (x,y): [4. 3.]


In [63]:
sales = np.array([1000, 1800, 1500, 1100, 1750, 1600, 1700, 2050, 2000, 1450])

print('Total Sales :',np.sum(sales))
print('Average Sales :',np.average(sales))
print('Minimum Sales :',np.min(sales))
print('Maximum Sales :',np.max(sales))

print('Sales Higher than Average :',sales[sales > np.average(sales)])

updated = sales * 1.1
print("Updated Sales :",updated)

print('Sorted Sales :',np.sort(sales))

Total Sales : 15950
Average Sales : 1595.0
Minimum Sales : 1000
Maximum Sales : 2050
Sales Higher than Average : [1800 1750 1600 1700 2050 2000]
Updated Sales : [1100. 1980. 1650. 1210. 1925. 1760. 1870. 2255. 2200. 1595.]
Sorted Sales : [1000 1100 1450 1500 1600 1700 1750 1800 2000 2050]
